plugins {
    id 'com.android.library'
}

android {
    namespace 'com.hermes.engine'
    compileSdk 34

    defaultConfig {
        minSdk 21
        targetSdk 34
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.7.1'
    implementation 'com.facebook.fbjni:fbjni:0.6.0'
}
