plugins {
    id 'com.android.library'
}

android {
    namespace 'com.hermes.wrapper.android'
    compileSdk 34

    defaultConfig {
        minSdk 21
        targetSdk 34
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation project(':wrapper-java')
    implementation project(':hermes-engine')
    implementation 'androidx.annotation:annotation:1.7.1'
}
